name: Acception Tests CI/CD

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*.*"
  pull_request:

permissions:
  contents: read

jobs:
  acc:
    name: Acception Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        harbor_deployments:
          - helm_chart_version: 1.4.0
            harbor_path: "/api/v2.0"
          - helm_chart_version: 1.4.1
            harbor_path: "/api/v2.0"
          # TODO: https://github.com/nolte/terraform-provider-harbor/issues/40
          #- helm_chart_version: 1.3.2
          #  harbor_path: "/api"
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: ^1.14
        id: go

      - name: Get dependencies
        run: |
          SWAGGER_VERSION=v0.23.0
          mkdir -p $HOME/bin
          curl -Lo $HOME/bin/swagger https://github.com/go-swagger/go-swagger/releases/download/${SWAGGER_VERSION}/swagger_linux_amd64 \
            && chmod +x $HOME/bin/swagger
          echo "::add-path::$HOME/bin"

      - name: install go stuff
        run: |
          go get -v \
           github.com/magefile/mage \
           github.com/evanphx/json-patch/cmd/json-patch
          echo "::add-path::$(go env GOPATH)/bin"

      - name: Check out code into the Go module directory
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: install golangci-lint
        run: |
          curl -sSfL -o /tmp/golangci-install.sh https://raw.githubusercontent.com/golangci/golangci-lint/2691aacde61559ce53cfda05513ee7c70677ea31/install.sh
          echo "9e99d38f3213411a1b6175e5b535c72e37c7ed42ccf251d331385a3f97b695e7  /tmp/golangci-install.sh" | sha256sum -c -
          sh /tmp/golangci-install.sh -b $(go env GOPATH)/bin v1.27.0

      - name: test provider
        run: |
          make generate

      # https://github.com/engineerd/setup-kind
      - uses: engineerd/setup-kind@4e17476a3712a9f6a6d99f9e1729b6cf7dbba86d # v0.4.0
        with:
          skipClusterCreation: true

      - name: Starting the Kind Cluster
        run: |
          ./scripts/tst-00-prepare-kind.sh

      - name: Testing
        run: |
          kind export kubeconfig
          kubectl cluster-info
          kubectl get pods -n kube-system
          NODEDNSNAME=$(kubectl get nodes -ojson | jq '.items[0].status.addresses[0].address' -r | sed 's/\./-/g')
          echo "::set-env name=INGRESS_DOMAIN::${NODEDNSNAME}.sslip.io"
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}

      - name: install helm3
        run: |
          curl -sfL -o /tmp/get-helm-3 https://raw.githubusercontent.com/helm/helm/bc0114c70841e2a05c95e53e20358fb761dbfb2e/scripts/get-helm-3
          echo "08edc9569a7115a22fdc4ec164a653d072440ad14a8dbe51ca9b321c903c59a9  /tmp/get-helm-3" | sha256sum -c -
          bash /tmp/get-helm-3

      - name: install harbor
        run: |
          ./scripts/tst-01-prepare-harbor.sh ${INGRESS_DOMAIN} "${{ matrix.harbor_deployments.helm_chart_version }}"
      #- name: install harbor
      #  run: |
      #    echo "::set-env name=INGRESS_DOMAIN::harbor.${NODEDNSNAME}.sslip.io"

      - name: Starting the Acc
        run: |
          ./scripts/tst-15-execute-go-acc.sh "${{ matrix.harbor_deployments.harbor_path }}"

      - name: remove the kind cluster
        if: ${{ always() }}
        run: |
          kind delete cluster

#
