name: Release Flow

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  releaseBuild:
    name: ReleaseBuild
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
        with:
          go-version: ^1.14
        id: go

      - name: Get dependencies
        run: |
          SWAGGER_VERSION=v0.23.0
          mkdir -p $HOME/bin
          curl -Lo $HOME/bin/swagger https://github.com/go-swagger/go-swagger/releases/download/${SWAGGER_VERSION}/swagger_linux_amd64 \
            && chmod +x $HOME/bin/swagger
          echo "::add-path::$HOME/bin"

      - name: install go stuff
        run: |
          go get -v \
           github.com/magefile/mage \
           github.com/evanphx/json-patch/cmd/json-patch
          echo "::add-path::$(go env GOPATH)/bin"

      - name: Check out code into the Go module directory
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: install golangci-lint
        run: |
          curl -sSfL -o /tmp/golangci-install.sh https://raw.githubusercontent.com/golangci/golangci-lint/2691aacde61559ce53cfda05513ee7c70677ea31/install.sh
          echo "9e99d38f3213411a1b6175e5b535c72e37c7ed42ccf251d331385a3f97b695e7  /tmp/golangci-install.sh" | sha256sum -c -
          sh /tmp/golangci-install.sh -b $(go env GOPATH)/bin v1.27.0

      - name: test provider
        run: |
          make generate
          make test

      - name: build provider
        run: |
          scripts/build-10-compile.sh ${GITHUB_REF##*/}

      - name: Upload Binaryies for publishing
        uses: actions/upload-artifact@ebad382c0953e8c6b4039e8d30dfd19ee7b2a862 # 2.1.0
        with:
          name: bin
          path: ${{ github.workspace }}/bin/**

  publish_docs:
    permissions:
      contents: write
    name: Publish the HTML Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@a31c6b13a80e4a4fbb525eeb7a2a78253bb15fa5 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_release_artefacts:
    permissions:
      contents: write
    name: Publish Release Artefacts
    runs-on: ubuntu-latest
    needs: [releaseBuild]
    steps:
      - uses: actions/download-artifact@cbed621e49e4c01b044d60f6c80ea4ed6328b281 # v2.1.1
        with:
          name: bin
      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@14569a2d348419d066e34e5dfa65071ecd30b64b # 1.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
