name: devcontainers

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - ".devcontainer/Dockerfile**"
      - .github/workflows/devcontainers.yml
  push:
    branches:
      - "**"
    paths:
      - ".devcontainer/Dockerfile**"
      - .github/workflows/devcontainers.yml

permissions:
  contents: read
  packages: read

jobs:
  devcontainers-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - uses: azure/docker-login@83efeb77770c98b620c73055fbb59b2847e17dc0 # v1.0.1
        with:
          login-server: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: buid vscode dev image
        run: |
          cd .devcontainer
          docker build -f Dockerfile .
  docscontainers-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: buid docs image
        run: |
          cd .devcontainer
          docker build -f DockerfileDocs .
