name: shellcheck

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**.sh"
      - .github/workflows/shellcheck.yml
  push:
    branches:
      - "**"
    paths:
      - "**.sh"
      - .github/workflows/shellcheck.yml

permissions:
  contents: read

jobs:
  shellcheck-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Lint check
        uses: azohra/shell-linter@6bbeaa868df09c34ddc008e6030cfe89c03394a1 # v0.6.0
